### ISSUE TITLE
Lizenzwechsel zu LGPL

### ISSUE THREAD

**Issue by willuhn** [willuhn/hbci4java#36]
Hallo,

ich werde immer mal wieder gefragt, ob ich die Lizenz von HBCI4Java denn nicht von der bisherigen GPLv2 auf LGPL ändern könnte, da es die Verwendung (verständlicherweise bei einer Programmbibliothek) vereinfachen würde.

Von meiner Seite aus ist das gar kein Problem. Leider ist es aber nicht so einfach. Es benötigt die Zustimmung aller Autoren, die Code zu HBCI4Java beigesteuert haben.

Der hier veröffentlichte Code ist ja ein Fork von http://hbci4java.kapott.org/index.html von Stefan. Für einen Lizenzwechsel braucht es also zu allererst seiner Zustimmung. Michael hat diese inzwischen von ihm erhalten.

Ich gebe mein OK ebenfalls. Damit bleiben jetzt noch all die anderen Contributoren, die hier Code beigesteuert haben. Michael bat mich, dieses Issue anzulegen - er würde dann alle anderen Contributoren kontaktieren, um deren Zustimmung einzuholen. 

Dein Task, Michael ;)

**Comment by AndiDog** [comment]
Meine Zustimmung habt ihr!

**Comment by kicktipp** [comment]
Weiß gar nicht, ob ich was beigetragen habe. Zustimmung natürlich trotzdem.

Am 25.08.2015 um 08:54 schrieb Olaf Willuhn:
> Hallo,
>
> ich werde immer mal wieder gefragt, ob ich die Lizenz von HBCI4Java denn
> nicht von der bisherigen GPLv2 auf LGPL ändern könnte, da es die
> Verwendung (verständlicherweise bei einer Programmbibliothek)
> vereinfachen würde.
>
> Von meiner Seite aus ist das gar kein Problem. Leider ist es aber nicht
> so einfach. Es benötigt die Zustimmung aller Autoren, die Code zu
> HBCI4Java beigesteuert haben.
>
> Der hier veröffentlichte Code ist ja ein Fork von
> http://hbci4java.kapott.org/index.html von Stefan. Für einen
> Lizenzwechsel braucht es also zu allererst seiner Zustimmung. Michael
> hat diese inzwischen von ihm erhalten.
>
> Ich gebe mein OK ebenfalls. Damit bleiben jetzt noch all die anderen
> Contributoren, die hier Code beigesteuert haben. Michael bat mich,
> dieses Issue anzulegen - er würde dann alle anderen Contributoren
> kontaktieren, um deren Zustimmung einzuholen.
>
> Dein Task, Michael ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/willuhn/hbci4java/issues/36>.
>

-- 
Kicktipp GmbH

Königstraße 9, 40212 Düsseldorf
Sitz der Gesellschaft: Düsseldorf
Geschäftsführung: Janning Vygen
Handelsregister Düsseldorf: HRB 55639

http://www.kicktipp.de/

**Comment by mpseidel** [comment]
@willuhn danke fürs Issue öffnen und danke @AndiDog und @kicktipp für die schnelle Rückmeldung! Ich frag mal rum, was die anderen meinen..

**Comment by shred** [comment]
Ich stimme der Änderung zu. Sehr gerne sogar! :-)

**Comment by hsch** [comment]
:+1:

**Comment by mpseidel** [comment]
Danke @shred @hsch fürs OK! Da ich von euch anderen Contributors keine Kontaktdaten finde oder noch nicht zurückgehört hab, hier nochmal der Aufruf an: @macemmi @fmms @jwolz @tbaum @waffel @machajdik @f1ori @ruderphilipp @tremlin @tlei: 

Wär für euch die Lizenzumstellung auch in Ordnung?

**Comment by jwolz** [comment]
Die Umstellung wäre für mich ebenfalls in Ordnung.

**Comment by f1ori** [comment]
bin voll dafür

**Comment by machajdik** [comment]
Für mich ok, falls noch was von mir drin ist!

Freundliche Grüße
Manuel Machajdik
Am 26.08.2015 8:22 nachm. schrieb "Michael Seidel" <notifications@github.com

**Comment by tlei** [comment]
Für mich auch ok (es war ja auch nicht viel von mir)

**Comment by macemmi** [comment]
Hallo,

ist für mich auch o.k.

Mit freundlichen Grüßen
Frank Emminghaus

Pecunia Development & Support
http://www.pecuniabanking.de

**Comment by tbaum** [comment]
Ein ok auch von mir. kein Problem damit


urlaubliche Grüße aus Italien 

/Thomas 


Excuse brevity and typos, sent from mobile device

**Comment by fmms** [comment]
Auch mein OK. Ich hoffe, dass die LGPL die Verbreitung und Beteiligung unterstützt.
Felix Möller

**Comment by ruderphilipp** [comment]
Für mich auch in Ordnung.

Philipp
Am 26.08.2015 20:22 schrieb "Michael Seidel" <notifications@github.com>:

**Comment by waffel** [comment]
Für mich geht das auch klar

- Thomas Wabner

**Comment by mpseidel** [comment]
Cool, danke euch. Laut der Liste https://github.com/willuhn/hbci4java/graphs/contributors fehlen nurnoch @tremlin und @joscha. Seid ihr auch dafür?

**Comment by AndiDog** [comment]
Der Graph zeigt mich z.B. nicht an (nur ein Pull Request) - vielleicht sind das nur die Top-Contributors? Nehmt lieber die Liste von

```bash
git log "--pretty=tformat:%an <%ae>" | sort | uniq
```

**Comment by joscha** [comment]
Hey, ja von meiner Seite aus kein Problem!

**Comment by tremlin** [comment]
Kein Problem von meiner Seite.

**Comment by willuhn** [comment]
@mpseidel - hast du 'nen Überblick, ob wir inzwischen schon alle nötigen OK haben?

**Comment by mpseidel** [comment]
@willuhn hey Olaf. Sorry für die lange Stille, bin aus dem Stress in den Urlaub und wieder zurück.
Also wir haben das ok von allen die in der GitHub-Contributer-Übersicht aufgelistet sind.
Wollte gerade noch @AndiDogs Hinweis nachgehen:

```
git log --all "--pretty=tformat:%an <%ae>" | sort | uniq

Felix Möller <mail@felixmoeller.de>
Hendrik Schnepel <hendrik.schnepel@gmail.com>
Jan Thielemann <jant@bea.iloq.de>
Janning Vygen <vygen@kicktipp.de>
Max Mustermann <muster@test.de>
Olaf Willuhn <github@willuhn.de>
Philipp Riemer <ruderphilipp@gmail.com>
Richard Körber <rk-github@cm4all.com>
macemmi <support@pecuniabanking.de>
willuhn <info@willuhn.de>
willuhn <willuhn>

```

Max Mustermann müssen wir wohl nicht fragen, aber Jan Thielemann schreibe ich noch an, den finde ich hier nur in der History und in Quellcodekommentaren und nicht als GitHub-user :)

**Comment by willuhn** [comment]
Cool. Da haben wir ja dann alle beisammen. ;)

**Comment by mpseidel** [comment]
Ich habe Jan auf Xing angeschrieben, aber noch keine Rückmeldung bekommen (ist laut Xing nicht aktiv da). Die E-Mailadresse funktioniert leider nicht. Hab ihn jetzt ein 2tes mal auf Xing angeschrieben. 

Das hier sind seine commits: https://github.com/willuhn/hbci4java/commits/master?author=jant@bea.iloq.de

**Comment by xxtesaxx** [comment]
Huhu,
also von mir aus könnt ihr mit meinem Code machen was ihr für richtig haltet. :) Es gibt nur eine Kleinigkeit die es noch zu klären gibt. Der von mir entwickelte Code wurde während meiner Arbeitszeit und im Auftrag meines ehemaligen Arbeitgebers, der evenos Consulting GmbH bzw. Jens Pfeiffer, entwickelt. Ich bin mir nicht 100% sicher wie die Rechtslage da aussieht aber ich denke letztendlich ist es seine und nicht meine Entscheidung. Ich glaube zwar nicht das er etwas dagegen haben wird aber fragen sollte man ihn vielleicht trotzdem.

LG
Jan Thielemann

**Comment by mpseidel** [comment]
@xxtesaxx Danke! Ich habe Herrn Pfeiffer auch noch kontaktiert.Dann sollten wir alle Zustimmungen beisammen haben.

**Comment by madmuffin1** [comment]
@mpseidel Ist die Zustimmung von Hr. Pfeiffer erfolgt oder noch ausstehend? Falls erfolgt, fehlt nun nur noch die Änderung der LICENCE-File und der entsprechenden Header? Wenn ja, würde ich gern einen entsprechenden PR vorbereiten.

**Comment by mpseidel** [comment]
@madmuffin1 hab keine Rückmeldung von ihm bekommen. Probier es gerne selber nochmal. 

P.S: ich bin kein Anwalt oder Experte in Softwarelizenzen. Also bitte selber nochmal prüfen ob du/ihr die Bibliothek auch nach einem Lizenz-PR nutzen könnt/wollt.

**Comment by shred** [comment]
Welchen (bzw. wieviel) Code hat Herr Pfeiffer beigetragen? Lohnt sich eventuell ein Rewrite?

**Comment by mpseidel** [comment]
@shred frag mal @xxtesaxx

**Comment by madmuffin1** [comment]
Ein kurzes `git log --author="jant@bea" --no-merges --format=oneline` gibt uns schon die nötige Information, was @xxtesaxx alles beigesteuert hat. Soweit ich das überblicken kann, geht es um die Geschäftsvorfälle SEPA Lastschriften und Überweisungen.

- 14f1328d8bdb3a1d1b9b16dd0d2dca63a775b49e Kleine anpassung
- 5729c21b31a547583364df35dac33f36c1af5251 Generator Klassen fuer GVLastSEPA erstellt. Sind aber noch jede menge todos und fixmes enthalten.
- 072a2206fa0c1e22718aaa4e6a9b64114eb4f5e5 Minimale Anpassungen
- af1ce04245d57c9426fb87684a9096732a2ce19a Kleine Änderungen an Tests und SEPA GVs
- 849dee5e7a986aa96a14f47a305edbef3293664f Restlichen GenUebSEPA Generator Klassen erstellt
- 04060a5daec0108a98464bffe2f1e46723aece46 Neue Generator Klassen und Anpassungen an GVUebSEPA und dem entsprechenden UnitTest
- 6a6ecb72f57b82bde16b6767592458e18efabbe4 Neue Dateien hinzugefügt für SEPA Überweisung und Unit Test. Anpassung der GVUebSEPA für die Nutzung von JAXB statt XMLCreator2
- 0f60d39106094eb564d221904d2bb7a6dc39102d Noch ein paar Dateien generiert und einen Typo in der build.xml beseitigt.
- b51a5dbaac7cbb1f8fac83563fc44724ff0ef3ff Weitere Dateien mit JAXB generiert
- 71e130f099101376c5c47f40098f9adb5b944573 Neue Dateien hinzugefügt
- 7ea9843e6b1c85aaece5d7755fc619bc10e9dd95 Schema 008.003.02
- eee8759cd5a4e7724bfbc8871e4aff386e2b4694 Neue Schemadateien

**Comment by willuhn** [comment]
Ich hab Jens von Evenos jetzt nochmal angeschrieben. Hatte vor 3 Jahren schonmal Kontakt mit ihm, als Jan den Code im Rahmen seiner Anstellung beigesteuert hat. Melde mich, wenn ich Antwort habe.

**Comment by willuhn** [comment]
Habe gerade Antwort von Jens erhalten: "ja das ist kein Problem. Der Lizenzwechsel ist für uns ok."

Damit haben wir jetzt alle beisammen, oder?

**Comment by madmuffin1** [comment]
Ein Abgleich der Liste aller Contributors (`git log --all "--pretty=tformat:%an <%ae>" | sort -u | uniq -u`) mit Link zur Zustimmung habe ich hier zusammengestellt: Wie es aussieht, fehlen nun noch @cthomaidis, @kjyv und @martinweck 

- [x] Andreas Sommer (https://github.com/willuhn/hbci4java/issues/36#issuecomment-134511423)
- [ ] cthomaidis <christos.thomaidis@transfact.de>
- [x] Felix Möller <mail@felixmoeller.de> (https://github.com/willuhn/hbci4java/issues/36#issuecomment-135160209)
- [x] Florian Richter <florian@richter-es.de> (https://github.com/willuhn/hbci4java/issues/36#issuecomment-135131755)
- [x] Hendrik Schnepel <hendrik.schnepel@gmail.com> (https://github.com/willuhn/hbci4java/issues/36#issuecomment-134872517)
- [x] Janning Vygen <vygen@kicktipp.de> (https://github.com/willuhn/hbci4java/issues/36#issuecomment-134513895)
- [x] Jan Thielemann <jant@bea.iloq.de> (https://github.com/willuhn/hbci4java/issues/36#issuecomment-213596401)
- [x] Joscha Feth <joscha@feth.com> (https://github.com/willuhn/hbci4java/issues/36#issuecomment-135767155)
- [x] jwolz <jwolz1@gmail.com> (https://github.com/willuhn/hbci4java/issues/36#issuecomment-135131747)
- [x] macemmi <support@pecuniabanking.de> (https://github.com/willuhn/hbci4java/issues/36#issuecomment-135152763)
- [x] machajdik <manuel.machajdik@gmail.com> (https://github.com/willuhn/hbci4java/issues/36#issuecomment-135131813)
- [ ] Martin Weck <martin.weck@gmx.net>
- [ ] ~~Max Mustermann <muster@test.de>~~
- [x] Olaf Willuhn <github@willuhn.de> (https://github.com/willuhn/hbci4java/issues/36#issue-102963081)
- [x] Philipp Riemer <ruderphilipp@gmail.com> (https://github.com/willuhn/hbci4java/issues/36#issuecomment-135351423)
- [x] Richard Körber <github@shredzone.org> (https://github.com/willuhn/hbci4java/issues/36#issuecomment-134696923)
- [x] Richard Körber <rk-github@cm4all.com> (https://github.com/willuhn/hbci4java/issues/36#issuecomment-134696923)
- [ ] Stefan Bethge <stefan+github@lanpartei.de>
- [x] Thomas Baum <thomas.baum@atns.de> (https://github.com/willuhn/hbci4java/issues/36#issuecomment-135159752)
- [x] Thomas Rehn <thomas.rehn@initos.com> (https://github.com/willuhn/hbci4java/issues/36#issuecomment-138227887)
- [x] tlei <github@tleine.de> (https://github.com/willuhn/hbci4java/issues/36#issuecomment-135132538)
- [x] waffel <waffel@hora-obscura.de> (https://github.com/willuhn/hbci4java/issues/36#issuecomment-135748873)
- [x] willuhn <info@willuhn.de> (https://github.com/willuhn/hbci4java/issues/36#issue-102963081)
- [x] willuhn <willuhn> (https://github.com/willuhn/hbci4java/issues/36#issue-102963081)

**Comment by willuhn** [comment]
Weisst du, ob die drei gleich eine Benachrichtigung kriegen, wenn du sie per @-Zeichen im Kommentar annotierst? Die beiden Patches von @cthomaidis und @martinweck waren ja erst vor Kurzem. Und die Änderung von @kjyv war nur eine Änderung der HBCI-Version bei der Postbank in der blz.properties.

Hier noch die zugehörigen Pull-Requests:

@cthomaidis - https://github.com/willuhn/hbci4java/pull/43
@martinweck - https://github.com/willuhn/hbci4java/pull/45
@kjyv - https://github.com/willuhn/hbci4java/pull/37

Falls ihr drei hierzu eine automatische Benachrichtigung von Github kriegt:Öffnet bitte einfach mal das Issue unter https://github.com/willuhn/hbci4java/issues/36 und gebt euer OK, wenn ein Lizenzwechsel von GPLv2 auf LGPL für euch OK ist. Danke!

**Comment by cthomaidis** [comment]
Von mir aus OK!

**Comment by martinweck** [comment]
Von mir aus auch OK

**Comment by willuhn** [comment]
Prima! Dann haben wir im Prinzip alles beisammen. Die Änderung von @kjyv war wie gesagt nur die geänderte HBCI-Version der Postbank in der blz.properties - also nicht wirklich Quellcode in dem Sinne.

**Comment by kjyv** [comment]
Trotzdem auch von mir gern ein OK (Banchrichtigung erst heute bekommen) ;)

**Comment by willuhn** [comment]
Danke! Damit ist es vollbracht, oder? ;)

**Comment by willuhn** [comment]
So, damit das Ticket jetzt endlich mal zugemacht werden kann - https://github.com/willuhn/hbci4java/commit/c5ac0b8f2705349d4f9513b84925dc0d323047b0

**Comment by mpseidel** [comment]
Cool - Danke an alle für die Zustimmung!

**Comment by Mailaender** [comment]
Das ZIP Paket unter https://github.com/willuhn/hibiscus/raw/V_2_6_17_BUILD_361/lib.src/hbci4java-2.5.12-src.zip enthält kein COPYING und die Header sagen immer noch GPL 2.0:

```java

/*  $Id: XMLEntity.java,v 1.1 2011/05/04 22:38:04 willuhn Exp $

    This file is part of HBCI4Java
    Copyright (C) 2001-2008  Stefan Palme

    HBCI4Java is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    HBCI4Java is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/
```

https://github.com/willuhn/hbci4java/blob/master/thirdparty/cryptalgs4java/doc/user/COPYING ist immer noch GPL 2.0

Genauso wie https://github.com/willuhn/hbci4java/blob/master/chipcard/src/tools/t_ddv_checkpin.cpp

Fehlende source tarballs https://github.com/willuhn/hbci4java/issues/42 ist bereits in Problem für die Linux-Paketierung. Widersprüchliche Angaben zur Lizenz machen es noch schwieriger.

**Comment by willuhn** [comment]
> Das ZIP Paket unter https://github.com/willuhn/hibiscus/raw/V_2_6_17_BUILD_361/
> lib.src/hbci4java-2.5.12-src.zip enthält kein COPYING

Wird im naechsten Release enthalten sein.
https://github.com/willuhn/hbci4java/commit/9c63929db6168a99b7642d832d384866131a1b1b

> https://github.com/willuhn/hbci4java/blob/master/thirdparty/cryptalgs4java/doc/user/COPYING
> ist immer noch GPL 2.0

https://github.com/willuhn/hbci4java/commit/9c63929db6168a99b7642d832d384866131a1b1b

Fuer die Aenderung der Header in allen Java-Quellcode-Dateien fehlt mir aber echt die Muse. Falls sich das jemand antun möchte, nehme ich den Pull-Request dafuer gern an.
